services:
  postgres:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4200:80"
    depends_on:
      - backend
    networks:
      - app-network
  # webinterface nodig?
  # OOIT gehoord van psql?
  # vooruit voor gemak:
  # env. var's veranderen? Doe je toch niet...
  #
  # pgadmin4:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  #
  # Voor als je postgres & pgadmin in 1 container wil,
  # uncomment onderstaande:
  # postgres_pgadmin:
  #   image: thajeztah/postgres-pgadmin
  #   ports:
  #     - "127.0.0.1:5433:5432"  # PostgreSQL
  #     - "127.0.0.1:5051:80"    # pgAdmin
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge
