spring.application.name=${SPRING_APPLICATION_NAME_LUXURY_PRODUCTS_WEBSHOP:BackendLuxuryProductsWebshop}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL_LUXURY_PRODUCTS_WEBSHOP}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_LUXURY_PRODUCTS_WEBSHOP}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_LUXURY_PRODUCTS_WEBSHOP}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET_LUXURY_PRODUCTS_WEBSHOP}
jwt.expiration=${JWT_EXPIRATION:3600000}

# CORS (wordt afgehandeld in CorsConfig.java, hoeft hier niet)

server.servlet.context-path=/api
server.error.include-message=always
server.port=${BACKEND_PORT_LUXURY_PRODUCTS_WEBSHOP:8080}
